### ISSUE TITLE
Deployment currently down

### ISSUE THREAD

**Issue by addyosmani** [oktay/movies#8]
Hey just a heads up that the Vercel deploy is currently down :)

https://movies-flax-sigma.vercel.app/

<img width="890" alt="image" src="https://github.com/oktay/movies/assets/110953/28c2bf4a-189f-42e6-ae47-becd1bb03d12">

**Comment by 7H3XXX** [comment]
Noticed it too, even after the latest commits.

**Comment by oktay** [comment]
Hello, I'm aware that the deployment is currently down. Unfortunately, I have to inform you that I had to disable the deployment to prevent it from being billed, as resource usage was approaching the limits of Vercel's "Hobby" plan.

![image](https://github.com/oktay/movies/assets/3390175/e2fb521e-5923-4f33-a60d-7d5d833b0792)
